; ASSEMBLY SCRIPT FOR 4 BIT VIRTUALIZATION

; MAX VALUE FOR INT: 15(16)

; ANSI MODE, NO LOWERCASE CHARS

; DEFINING NUMBER LIMITS FOR INTEGERS (4 BIT MODE)
MAXA = 15
MAXB = 16
MINA = -15
MINB = -16

; CURRENTLY UNUSABLE

; FILE VERSION: 1 (MAY 27TH 2020)
