# Project language file 50

## For: WacOS

### About

I chose the API Blueprint language as the 50th language file for this project (seanpm2001/WacOS) as this language first started being used on this project on 2022 May 12th (after uploading a blueprint from 2022 May 10th) it is being used for hardware blueprints.

### File info

File type: API Blueprint source file (.apib)
File version: 1 (2022, Thursday, May 12th at 7:35 pm PST)
Line count (including blank lines and compiler line): 14
