'\" t
.\"     Title: WacOS Manual for the BaSYS subsystem
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2022/01/13@17:54
.\"    Manual: Git Manual
.\"    Source: Nil
.\"  Language: English (US)
.\"
.TH "GIT\-ADD" "1" "12/10/2021" "Git 2\&.34\&.1\&.182\&.ge77354" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-add \- Add file contents to the index
.SH "SYNOPSIS"
.sp
.nf
\fIgit add\fR [\-\-verbose | \-v] [\-\-dry\-run | \-n] [\-\-force | \-f] [\-\-interactive | \-i] [\-\-patch | \-p]
          [\-\-edit | \-e] [\-\-[no\-]all | \-\-[no\-]ignore\-removal | [\-\-update | \-u]] [\-\-sparse]
          [\-\-intent\-to\-add | \-N] [\-\-refresh] [\-\-ignore\-errors] [\-\-ignore\-missing] [\-\-renormalize]
          [\-\-chmod=(+|\-)x] [\-\-pathspec\-from\-file=<file> [\-\-pathspec\-file\-nul]]
          [\-\-] [<pathspec>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
This is the manual for the WacOS operating system project that goes over the WacOS BaSYS Subsystem.\&.
.sp
.SH "BaSYS"
.sp
## BaSYS
[View source code for BaSYS](/BaSYS/)
WacOS contains subsystems for every Apple product. BaSYS is a sub-operating system project meant to emulate the first 7 major versions of classic MacOS
BaSYS 1 - Emulates Apple System 1
BaSYS 2 - Emulates Apple System 2
BaSYS 3 - Emulates Apple System 3
BaSYS 4 - Emulates Apple System 4
BaSYS 5 - Emulates Apple System 5
BaSYS 6 - Emulates Apple System 6
BaSYS 7 - Emulates Apple System 7 (but not MacOS 7.5)
.sp
.SH "Footer"
.sp
This manpage was last updated on 2022 Thursday, January 13th at 5:54 pm (Version 1.0)
.sp
