# Start of script
# GitHub issue data file (YAML) for WacOS
issuelabel_1: color1: "#ffffff" title1: "wontfix" description1: "This will not be worked on"
issueLabel_2: color2: "#d876e3" title2: "question" description2: "Further information is requested"
issueLabel_3: color3: "#e4e669" title3: "invalid" description3: "This doesn't seem right"
issueLabel_4: color4: "#008672" title4: "help wanted" description4: "Extra attention is needed"
issueLabel_5: color5: "#7057ff" title5: "good first issue" description5: "Good for newcomers"
issueLabel_6: color6: "#a2eeef" title6: "enhancement" description6: "New feature or request"
issueLabel_7: color7: "#cfd3d7" title7: "duplicate" description7: "This issue or pull request already exists"
issueLabel_8: color8: "#0075ca" title8: "documentation" description8: "Improvements or additions to documentation"
issueLabel_9: color9: "#d73a4a" title9: "bug" description9: "Something isn't working"
issueLabel_10: color10: "#0EC0F9" title10: "wOS" description10: "For issues related to the wOS subsystem."
issueLabel_11: color11: "#B2C6E9" title11: "WoahS-X" description11: "For issues related to the WoahS X subsystem."
issueLabel_12: color12: "#1D76DB" title12: "Wiki" description12: "For issues related to the WacOS project Wiki."
issueLabel_13: color13: "#E99695" title13: "WhyWatchOS" description13: "For issues related to the WhyWatchOS Subsystem."
issueLabel_14: color14: "#46BBEA" title14: "WhyPhoneOS" description14: "For issues related to the WhyPhoneOS subsystem."
issueLabel_15: color15: "#006B75" title15: "WhyPadOS" description15: "For issues related to WhyPadOS."
issueLabel_16: color16: "#0E3FBC" title16: "WAMMY" description16: "For issues related to the WAMMY subproject."
issueLabel_17: color17: "#A68AE2" title17: "WacWrite" description17: "For issues related to the Wac Write software piece."
issueLabel_18: color18: "#F9D0C4" title18: "WacPaint" description18: "For issues related to the Wac Paint software piece."
issueLabel_19: color19: "#557216" title19: "WacOS Server" description19: "For issues related to the WacOS server framework."
issueLabel_20: color20: "#232FE6" title20: "WacOS Cloud" description20: "For issues related to the WacOS online storage system."
issueLabel_21: color21: "#1C0C45" title21: "Wac TvOS" description21: "For issues related to the Wac TvOS subsystem."
issueLabel_22: color22: "#0052CC" title22: "Wac OS X" description22: "For issues related to the Wac OS X subsystem."
issueLabel_23: color23: "#1D5EA4" title23: "VHDL" description23: "For issues on the topic of VHDL source code."
issueLabel_24: color24: "#BE98FE" title24: "Vanilla PHP" description24: "For issues on the topic of the WacOS Vanilla PHP implementation."
issueLabel_25: color25: "#5319E7" title25: "Unicode" description25: "For issues on the topic of Unicode."
issueLabel_26: color26: "#3D671C" title26: "Themes" description26: "For issues related to WacOS themes."
issueLabel_27: color27: "#4C5586" title27: "System 7" description27: "For issues on the topic of Apple System 7 (but NOT MacOS 7)"
issueLabel_28: color28: "#4C5586" title28: "System 6" description28: "For issues on the topic of Apple System 6."
issueLabel_29: color29: "#4C5586" title29: "System 5" description29: "For issues on the topic of Apple System 5."
issueLabel_30: color30: "#4C5586" title30: "System 4" description30: "For issues on the topic of Apple System 4."
issueLabel_31: color31: "#4C5586" title31: "System 3" description31: "For issues on the topic of Apple System 3."
issueLabel_32: color32: "#4C5586" title32: "System 2" description32: "For issues on the topic of Apple System 2."
issueLabel_33: color33: "#4C5586" title33: "System 1" description33: "For issues on the topic of Apple System 1"
issueLabel_34: color34: "#B60205" title34: "Syntax errors" description34: "For syntax errors in the source code."
issueLabel_35: color35: "#CB1D69" title35: "Swift" description35: "For issues on the topic of Swift source code."
issueLabel_36: color36: "#7C94B8" title36: "Submodules" description36: "For issues related to Git submodules."
issueLabel_37: color37: "#000000" title37: "Spam" description37: " For spam issues. "
issueLabel_38: color38: "#BD566E" title38: "Skeuowie" description38: "For issues related to WacOS support for the S Desktop environment (Skeuowie)"
issueLabel_39: color39: "#D93F0B" title39: "Sir Isaac NewtonScript" description39: "For issues related to the Sir Isaac NewtonScript subproject."
issueLabel_40: color40: "#94EF8D" title40: "Sir Isaac NewtonOS" description40: "For issues related to the Sir Isaac Newton Subsystem."
issueLabel_41: color41: "#507605" title41: "Shell" description41: "For issues on the topic of Shell source code."
issueLabel_42: color42: "#0A5D40" title42: "Self" description42: "For issues on the topic of Self source code."
issueLabel_43: color43: "#0E8A16" title43: "Savannah" description43: "For issues related to the Savannah web browser."
issueLabel_44: color44: "#47E7C2" title44: "Runtime error" description44: "For Runtime errors."
issueLabel_45: color45: "#5319E7" title45: "Quantum" description45: "For issues related to quantum computer support."
issueLabel_46: color46: "#FBCA04" title46: "Q#" description46: "For issues on the topic of Q# source code."
issueLabel_47: color47: "#0052CC" title47: "Python" description47: "For issues on the topic of Python source code."
issueLabel_48: color48: "#7032A5" title48: "Prolog" description48: "For issues on the topic of Prolog source code."
issueLabel_49: color49: "#5319E7" title49: "PHP" description49: "For issues on the topic of PHP source code."
issueLabel_50: color50: "#FEF2C0" title50: "Pascal" description50: "For issues related to Pascal source code."
issueLabel_51: color51: "#778D30" title51: "OpenCyberdog" description51: "For issues related to the OpenCyberdog web browser."
issueLabel_52: color52: "#B60205" title52: "OpenAPFS" description52: "For issues related to the Open APFS file system."
issueLabel_53: color53: "#D4C5F9" title53: "Objective-C++" description53: "For issues on the topic of Objective-C++ source code."
issueLabel_54: color54: "#6DB1FB" title54: "Objective-C" description54: "For issues on the topic of Objective-C source code."
issueLabel_55: color55: "#006B75" title55: "MacOS 9" description55: "For issues on the topic of MacOS 9."
issueLabel_56: color56: "#C5DEF5" title56: "MacOS 8" description56: "For issues on the topic of MacOS 8."
issueLabel_57: color57: "#F9D0C4" title57: "MacOS 7" description57: "For issues on the topic of MacOS 7 (but NOT Apple System 7)"
issueLabel_58: color58: "#93B62B" title58: "Localization" description58: "For issues related to localization and linguistic/language support/problems."
issueLabel_59: color59: "#FBCA04" title59: "Linux" description59: "For issues regarding Linux compatibility with WacOS."
issueLabel_60: color60: "#BE98FE" title60: "Laravel PHP framework" description60: "For issues on the topic of the WacOS Laravel PHP framework implementation."
issueLabel_61: color61: "#8946A0" title61: "Kiri" description61: "For issues related to the Kiri voice assistant."
issueLabel_62: color62: "#0052CC" title62: "Kernel" description62: "For Kernel related issues."
issueLabel_63: color63: "#FBCA04" title63: "JavaScript" description63: "For issues on the topic of JavaScript source code."
issueLabel_64: color64: "#D93F0B" title64: "Java" description64: "For issues on the topic of Java source code."
issueLabel_65: color65: "#FBCA04" title65: "Issue" description65: "For WacOS project issues that are raised."
issueLabel_66: color66: "#143455" title66: "iPhoneOS" description66: "For issues related to iPhoneOS (but NOT iOS)"
issueLabel_67: color67: "#BFD4F2" title67: "iOS" description67: "For issues related to iOS (but NOT iPhoneOS)"
issueLabel_68: color68: "#D93F0B" title68: "HTML" description68: "For issues on the topic of HTML source code."
issueLabel_69: color69: "#842EE8" title69: "HFS+" description69: "For issues related to the HFS+ file system."
issueLabel_70: color70: "#DDDA6A" title70: "HFS" description70: "For issues related to the HFS file system."
issueLabel_71: color71: "#EDC02F" title71: "Goal" description71: "For project goals."
issueLabel_72: color72: "#51FA36" title72: "File system" description72: "For issues on the topic of file systems."
issueLabel_73: color73: "#E853F2" title73: "ext4" description73: "For issues related to the ext4 file system."
issueLabel_74: color74: "#006B75" title74: "Drivers" description74: "For driver issues."
issueLabel_75: color75: "#BFD4F2" title75: "Donation" description75: "For source code donations."
issueLabel_76: color76: "#0E8A16" title76: "Discussion" description76: "For WacOS project discussions."
issueLabel_77: color77: "#5319E7" title77: "Darwin" description77: "For issues regarding Darwin compatibility with WacOS."
issueLabel_78: color78: "#474DCA" title78: "CSS" description78: "For issues on the topic of CSS source code."
issueLabel_79: color79: "#5319E7" title79: "C++" description79: "For issues on the topic of C++ source code."
issueLabel_80: color80: "#5755C0" title80: "C" description80: "For issues on the topic of C source code."
issueLabel_81: color81: "#1d76db" title81: "BaSYS" description81: "For issues related to the BaSYS subsystem for Classic MacOS (1-6)"
issueLabel_82: color82: "#FBA111" title82: "Assembly" description82: "For issues on the topic of Assembly source code."
issueLabel_83: color83: "#7E49F6" title83: "AppleScript" description83: "For issues on the topic of AppleScript source code."
issueLabel_84: color84: "#B60205" title84: "APFS" description84: "For issues related to the APFS file system."
issueLabel_85: color85: "#006b75" title85: "Memory management" description85: "For issues on the topic of memory management."
issueLabel_86: color86: "#F9D0C4" title86: "Man page" description86: "For issues on the topic of manual pages in Roff format."
issueLabel_87: color87: "#D5C4D6" title87: "SWAP Memory" description87: "For issues on the topic of SWAP Memory."
issueLabel_88: color88: "#FEF2C0" title88: "ROFF" description88: "For issues on the topic of ROFF source code"
issueLabel_89: color89: "#5319E7" title89: "SWAP Maker" description89: "For issues related to the SWAP Maker component."
issueLabel_90: color90: "#FBCA04" title90: "News (file)" description90: "For issues on the topic of the NEWS file, improvements, additions, deductions, and edits."
issueLabel_91: color91: "#7901E8" title91: "OS Config (file)" description91: "For issues on the topic of the OSCONFIG.YML file, improvements, additions, deductions, and edits."
issueLabel_92: color92: "#006b75" title92: "Legal" description92: "For issues on the topic of legality."
issueLabel_93: color93: "#C213CD" title93: "Review needed" description93: "For issues that need review."
issueLabel_94: color94: "#0052CC" title94: "Credits" description94: "For issues on the topic of credits and crediting contributors."
issueLabel_95: color95: "#e99695" title95: "Maintenance" description95: "For issues related to maintenance of the WacOS project."
issueLabel_96: color96: "" title96: "" description96: ""
issueLabel_97: color97: "" title97: "" description97: ""
issueLabel_98: color98: "" title98: "" description98: ""
issueLabel_99: color99: "" title99: "" description99: ""
issueLabel_100: color100: "" title100: "" description100: ""
issueLabel_101: color101: "" title101: "" description101: ""
issueLabel_102: color102: "" title102: "" description102: ""
issueLabel_103: color103: "" title103: "" description103: ""
issueLabel_104: color104: "" title104: "" description104: ""
issueLabel_105: color105: "" title105: "" description105: ""
issueLabel_106: color106: "" title106: "" description106: ""
issueLabel_107: color107: "" title107: "" description107: ""
issueLabel_108: color108: "" title108: "" description108: ""
issueLabel_109: color109: "" title109: "" description109: ""
issueLabel_110: color110: "" title110: "" description110: ""
issueLabel_111: color111: "" title111: "" description111: ""
issueLabel_112: color112: "" title112: "" description112: ""
issueLabel_113: color113: "" title113: "" description113: ""
issueLabel_114: color114: "" title114: "" description114: ""
issueLabel_115: color115: "" title115: "" description115: ""
issueLabel_116: color116: "" title116: "" description116: ""
issueLabel_117: color117: "" title117: "" description117: ""
issueLabel_118: color118: "" title118: "" description118: ""
issueLabel_119: color119: "" title119: "" description119: ""
# Users can also create their own issue labels, and customize the color, title, and description
# issueLabel_10: color10: "#000000" title10: "void" description10: "not yet created"
# No known limit on # of issue labels
# File info
# File type: YAML source file (*.yml *.yaml)
# File version: 2 (2022, Friday, January 14th at 8:18 pm)
# Line count (including blank lines and compiler line): 1300
# End of file
