'\" t
.\"     Title: WacOS Manual for the WacOS Font libraries
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2022/01/13@18:09
.\"    Manual: Git Manual
.\"    Source: Nil
.\"  Language: English (US)
.\"
.TH "GIT\-ADD" "1" "12/10/2021" "Git 2\&.34\&.1\&.182\&.ge77354" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-add \- Add file contents to the index
.SH "SYNOPSIS"
.sp
.nf
\fIgit add\fR [\-\-verbose | \-v] [\-\-dry\-run | \-n] [\-\-force | \-f] [\-\-interactive | \-i] [\-\-patch | \-p]
          [\-\-edit | \-e] [\-\-[no\-]all | \-\-[no\-]ignore\-removal | [\-\-update | \-u]] [\-\-sparse]
          [\-\-intent\-to\-add | \-N] [\-\-refresh] [\-\-ignore\-errors] [\-\-ignore\-missing] [\-\-renormalize]
          [\-\-chmod=(+|\-)x] [\-\-pathspec\-from\-file=<file> [\-\-pathspec\-file\-nul]]
          [\-\-] [<pathspec>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
This is the manual for the WacOS operating system project that goes over the default fonts in WacOS.\&.
.sp
.SH "Fonts"
.sp
# Fonts
[View the fonts sub-repo](/Fonts/)
WacOS supports all the standard Apple fonts, along with others. I also plan to support some rare, but historical ones, such as blackletter.
### Apple fonts
WacOS currently supports the following Apple fonts:
- [x] Chicago
- [x] Monaco
- [ ] Garamond
- [x] Charcoal
- [x] Geneva
- [ ] Shaston
- [ ] Espy Sans
- [ ] Lucida Grande
- [ ] Podium Sans
- [x] Helvetica
- [ ] San Francisco
- [ ] New York
- [ ] Motter Tektura
- [x] Gill Sans
- [x] Myriad
The fonts are in OTF, TTF, and WOFF formats. The fonts used are free to use, as long as they are not sold for a profit.
### Other fonts
No other fonts are currently in use
.sp
.SH "Footer"
.sp
This manpage was last updated on 2022 Thursday, January 13th at 6:09 pm (Version 1.0)
.sp
