blank_issues_enabled: false
contact_links:
  - name: The program won't run/can't install
    url: https://github.com/seanpm2001/Git-image/tree/WacOS-dev/Docs/Installation/
    about: This question will be ignored if asked. Please read the docs.
  - name: I want to help develop
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start developing with me
  - name: I want to help develop an operating system with you, but not like this
    url: https://github.com/seanpm2001/Seanpm2001-Operating-Systems
    about: I have several operating system projects, WacOS is just one of them. This list contains all of them
  - name: I want to help translate
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start translating projects with me

# File info
# File version: 1 (2022, Wednesday, May 25th at 2:45 pm PST)
# File type: GitHub issue template config file (*.yml)
# Line count (including blank lines and compiler line): 20
