name: Miscellaneous
description: Write a general issue without too much questioning
body:
  - type: markdown
    attributes:
      value: |
        Unknown
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I verified that this is not an existing issue
          required: true
        - label: This is not a question, poll, or discussion
          required: true
        - label: I checked the documentation to understand that the issue I report is not a normal behavior
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Your issue description. Make sure to utilize Markdown to make your life easier :)
    validations:
      required: true
# File info
# File type: GitHub bug report issue template (*.yml)
# File version: 1 (2022, Wednesday, November 23rd at 6:31 pm PST)
# Line count (including blank lines and compiler line): 30
