10 PRINT 
20 PRINT 
30 PRINT 
40 PRINT "                      XXXX"
50 PRINT "                     X    XX"
60 PRINT "                    X  ***  X                XXXXX"
70 PRINT "                   X  *****  X            XXX     XX"
80 PRINT "                XXXX ******* XXX      XXXX          XX"
90 PRINT "              XX   X ******  XXXXXXXXX                XX XXX"
100 PRINT "            XX      X ****  X                           X** X"
110 PRINT "           X        XX    XX     X                      X***X"
120 PRINT "          X         //XXXX       X                      XXXX"
130 PRINT "         X         //   X                             XX"
140 PRINT "        X         //    X          XXXXXXXXXXXXXXXXXX/"
150 PRINT "        X     XXX//    X          X"
160 PRINT "        X    X   X     X         X"
170 PRINT "        X    X    X    X        X"
180 PRINT "         X   X    X    X        X                    XX"
190 PRINT "         X    X   X    X        X                 XXX  XX"
200 PRINT "          X    XXX      X        X               X  X X  X"
210 PRINT "          X             X         X              XX X  XXXX"
220 PRINT "           X             X         XXXXXXXX\     XX   XX  X"
230 PRINT "            XX            XX              X     X    X  XX"
240 PRINT "              XX            XXXX   XXXXXX/     X     XXXX"
250 PRINT "                XXX             XX***         X     X"
260 PRINT "                   XXXXXXXXXXXXX *   *       X     X"
270 PRINT "                                *---* X     X     X"
280 PRINT "                               *-* *   XXX X     X"
290 PRINT "                               *- *       XXX   X"
300 PRINT "                              *- *X          XXX"
310 PRINT "                              *- *X  X          XXX"
320 PRINT "                             *- *X    X            XX"
330 PRINT "                             *- *XX    X             X"
340 PRINT "                            *  *X* X    X             X"
350 PRINT "                            *  *X * X    X             X"
360 PRINT "                           *  * X**  X   XXXX          X"
370 PRINT "                           *  * X**  XX     X          X"
380 PRINT "                          *  ** X** X     XX          X"
390 PRINT "                          *  **  X*  XXX   X         X"
400 PRINT "                         *  **    XX   XXXX       XXX"
410 PRINT "                        *  * *      XXXX      X     X"
420 PRINT "                       *   * *          X     X     X"
430 PRINT "         =======*******   * *           X     X      XXXXXXXX\"
440 PRINT "                *         * *      /XXXXX      XXXXXXXX\      )"
450 PRINT "           =====**********  *     X                     )  \  )"
460 PRINT "             ====*         *     X               \  \   )XXXXX"
470 PRINT "        =========**********       XXXXXXXXXXXXXXXXXXXXXX"
480 PRINT 
490 PRINT 
500 PRINT "COMPLIMENTS OF THE COMPONENTS GROUP VIA THE LSI-11"
510 PRINT 
520 END

