'\" t
.\"     Title: WacOS Manual for WacOS Language package support
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2022/01/13@17:35
.\"    Manual: Git Manual
.\"    Source: Nil
.\"  Language: English (US)
.\"
.TH "GIT\-ADD" "1" "12/10/2021" "Git 2\&.34\&.1\&.182\&.ge77354" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-add \- Add file contents to the index
.SH "SYNOPSIS"
.sp
.nf
\fIgit add\fR [\-\-verbose | \-v] [\-\-dry\-run | \-n] [\-\-force | \-f] [\-\-interactive | \-i] [\-\-patch | \-p]
          [\-\-edit | \-e] [\-\-[no\-]all | \-\-[no\-]ignore\-removal | [\-\-update | \-u]] [\-\-sparse]
          [\-\-intent\-to\-add | \-N] [\-\-refresh] [\-\-ignore\-errors] [\-\-ignore\-missing] [\-\-renormalize]
          [\-\-chmod=(+|\-)x] [\-\-pathspec\-from\-file=<file> [\-\-pathspec\-file\-nul]]
          [\-\-] [<pathspec>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
This is the manual for the WacOS operating system project that goes over the WacOS language package support system.\&.
.sp
.SH "Language package support"
.sp
## Language package support
WacOS uses 45 different computing, configuration, markup, and programming languages, including:
C
C++
Objective-C
Assembly
VHDL (Virtual Hard Disk Language)
Python (3.6 and up for modern portions)
Swift (5.7 and up for modern portions)
AppleScript
Pascal
Self
Shell (BASH)
YAML (YAML Ain't Markup Language)
Markdown
Prolog
PHP (PHP HyperText Preprocessor)
Java
SQL (Structed Query Language)
Ruby
Perl
SVG (Scalable Vector Graphics)
XML (eXtensible Markup Language)
Makefile (GNU Make)
JavaScript
Q#
Desktop (KDE Desktop configuration file)
INI (Windows INI)
Plain Text
HTML (HyperText Markup Language)
CSS (Cascade Styling Sheets)
WebVTT (Web Video Text Tracks)
TypeScript
Metal
Objective-C++
Rust
PostScript
TeX (LaTeX and BibTeX)
m4
OpenEdge ABL
Verilog
SystemVerilog
Verilog AMS
Smalltalk
AssemblyScript
JavaScript++ (JS++)
JSON (JavaScript Object Notation)
.sp
.SH "Footer"
.sp
This manpage was last updated on 2022 Thursday, January 13th at 5:35 pm (Version 1.0)
.sp
