
## Project language file 1

### For: WacOS/Hardware_Blueprints

### About:

I have decided to make API Blueprint the first project language for this project (WacOS/Hardware_Blueprints) as I chose this as the core language for blueprints of WacOS hardware. It will be supplemented with another language in the future. It is getting its own project language file, starting here.

### File info

File version: 1 (2022, Sunday, May 15th at 6:02 pm PST)

File type: API Blueprint source file (.apib)

Line count (including blank lines and compiler line): 17
