'\" t
.\"     Title: WacOS Manual for language usage
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2022/01/13@16:47
.\"    Manual: Git Manual
.\"    Source: Nil
.\"  Language: English (US)
.\"
.TH "GIT\-ADD" "1" "12/10/2021" "Git 2\&.34\&.1\&.182\&.ge77354" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-add \- Add file contents to the index
.SH "SYNOPSIS"
.sp
.nf
\fIgit add\fR [\-\-verbose | \-v] [\-\-dry\-run | \-n] [\-\-force | \-f] [\-\-interactive | \-i] [\-\-patch | \-p]
          [\-\-edit | \-e] [\-\-[no\-]all | \-\-[no\-]ignore\-removal | [\-\-update | \-u]] [\-\-sparse]
          [\-\-intent\-to\-add | \-N] [\-\-refresh] [\-\-ignore\-errors] [\-\-ignore\-missing] [\-\-renormalize]
          [\-\-chmod=(+|\-)x] [\-\-pathspec\-from\-file=<file> [\-\-pathspec\-file\-nul]]
          [\-\-] [<pathspec>\&...]
.fi
.sp
.SH "DESCRIPTION"
.sp
This is the manual for the WacOS operating system project that goes over development requirements.\&.
.sp
.sp
.SH "Languages"
.sp
## Human-spoken languages
> Currently, the program is only supplied in the English language. Multi-lingual support for over 100 languages is planned for the future.
**Languages are listed in A-Z order**
> 001. English
> 002. No other human spoken languages listed.
### Computer languages
**Languages are listed in A-Z order**
> 01. AppleScript | Type: Programming language
> 02. Assembly | Type: Programming language
> 03. C | Type: Programming language
> 04. C++ | Type: Programming language
> 05. Markdown | Type: Markup language
> 06. Motorola S-RECORD | Type: Programming language
> 07. Objective-C | Type: Programming language
> 08. Python | Type: Programming language
> 09. Swift | Type: Programming language
> 10. SVG (Scalable Vector Graphics) | type: Raster graphics
> 11. Text | Type: Plain Text
> 12. Virtual Hard Disk Language (VHDL) | Type: Programming language
> 13. XML (eXtensive Markup Language) | type: Markup language
> 14. No other computer/programming languages listed.
.sp
.SH "Footer"
.sp
This manpage was last updated on 2022 Thursday, January 13th at 4:47 pm (Version 1.0)
.sp
