// Start of script
// BaSYS System 3 headers

// Fonts
#include </FONT/MONACO.TTF>
#include </FONT/CHICAGO.TTF>

// System files
#include </MAIN.C>
#include </MAIN.H>

// Graphics
#include </trash_empty.png">
#include </systemdisk.png>
#include </roundtopleft.png>
#include </roundtopright.png>

// Runtime
#include </c.c>
#include </c.h>
#include </PAS.pas>
#include </ASM.asm>

/* File info
* File type: C header file (*.h)
* File version: 1 (2021, December 22nd at 3:39 pm)
* Line count (including blank lines and compiler line): 30
*/
// End of script
