"Start of script"
"Project language 42"
"For: WacOS"
"About:"
Transcript show: 'I decided to make Smalltalk the forty-second project language file for this project (Seanpm2001/WacOS) as Smalltalk is a good language for some portions of this project, such as the SirIsaacNewtonOS project, which will be based off the original design. it can be used for some portions of this project. It is being included for software diversity reasons, and will be used for some portions of the project. It is getting its own project language file, starting here.'.
"File info:"
"File type: Smalltalk source file (*.st)"
"File version: 1 (2021, Friday, December 24th at 4:47 pm)"
"Line count (including blank lines and compiler line): 11"
" End of script
