# wPod First Edition

## Hardware Blueprints

These are the hardware blueprints for the first edition wPod, an aethetical and open approach to the iPod Classic, with modern capabilities and features.

### Construction

Requires:

A 3D printer (for the case)

A microSD card (as much storage as you want)

TouchScreen.unknown

ClassiPadRoller.unknown

Raspberry_Pi_Nano.unknown

### ClassiPad Roller

A rollup click pad that goes over half of the touchscreen to give off iPod Classic aethetics. Optionally, touch screen support can be disabled when this is enabled, and the screen resolution will change to match the view
